### ISSUE TITLE
Ondato crashes at the end on iOS 

### ISSUE THREAD

**Issue by agnesemonaviciute** [ondato/ondato-sdk-ios#11]
Hello, I am using iOS 17.2.1. I am going through the Ondato flow with passport. However, when I reach the last screen, which is sending data, after that I get a black screen and cannot proceed further.

I am using 2.5.2 OndatoSDK version

**Comment by Svaike** [comment]
Hi @agnesemonaviciute,

please contact me at svajunas.gaina@ondato.com - I need the details about the client/setup configuration to reproduce the issue.
