### ISSUE TITLE
ITMS-91065: Missing signature with v2.5.5

### ISSUE THREAD

**Issue by dmi3j** [ondato/ondato-sdk-ios#13]
Ondato iOS SDK: 2.5.5
Xcode: 15.4
Injection method: SPM (Swift Package Manager)

When build submitted to TestFlight, the error from Apple review team received:

> ITMS-91065: Missing signature - Your app includes “Frameworks/OpenSSL.framework/OpenSSL”, which includes BoringSSL / openssl_grpc, an SDK that was identified in the documentation as a privacy-impacting third-party SDK. If a new app includes a privacy-impacting SDK, or an app update adds a new privacy-impacting SDK, the SDK must include a signature file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a signature. For details about verifying the code signature for a third-party SDK, visit: https://developer.apple.com/documentation/xcode/verifying-the-origin-of-your-xcframeworks.

**Comment by ondato-mobile** [comment]
@dmi3j Signature has been added, see release 2.5.6.
