### ISSUE TITLE
Asset validation failed

### ISSUE THREAD

**Issue by melanu1991** [ondato/ondato-sdk-ios#14]
Ondato iOS SDK: 2.5.2
Xcode: 16.0.beta3
Injection method: Cocoapods

During the submission of a build to AppStoreConnect, the error from Apple received:
Invalid Executable. The executable 'AppName.app/Frameworks/FaceTecSDK.framework/FaceTecSDK' contains bitcode.
Invalid Executable. The executable 'AppName.app/Frameworks/OpenSSL.framework/OpenSSL' contains bitcode.

**Comment by melanu1991** [comment]
If there is any progress? Xcode 16 was released and we are still facing the same issue.

**Comment by ondato-mobile** [comment]
@melanu1991 [2.5.11](https://github.com/ondato/ondato-sdk-ios/releases/tag/2.5.11) is bitcode free

**Comment by mindaugasp-ondato** [comment]
@melanu1991 Please let us know if you still have any issues with this version.
