### ISSUE TITLE
Swift Compiler Error (Xcode): Could not find module 'OndatoSDK' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios

### ISSUE THREAD

**Issue by chinloyal** [ondato/ondato-sdk-ios#5]
It seems the SDK was only built to run on physical iOS devices and not on a simulator on the lastest version.

If you compare v1.8.19 with 1.8.14 in the OndatoSDK.framework/Modules/OndatoSDK.swiftmodule directory, you'll see the missing archs

**Comment by melanu1991** [comment]
any news about this bad boy? the same problem for me...

**Comment by chinloyal** [comment]
> any news about this bad boy? the same problem for me...

The workaround is to just use v1.8.14 for now

**Comment by melanu1991** [comment]
I used to it a few weeks ago it sounds crazy. Or you can use only real device...

**Comment by chinloyal** [comment]
For versions after 1.8.14 you have to use a real device
