### ISSUE TITLE
Crash in version 2.1.0 after calling Ondato.sdk.instantiateOndatoViewController()

### ISSUE THREAD

**Issue by glebpreger** [ondato/ondato-sdk-ios#8]
Hi, I have EXC_BAD_ACCESS error inside RxSwift after calling Ondato.sdk.instantiateOndatoViewController().
Can you help me to fix this problem?

<img width="1437" alt="Screenshot 2022-11-02 at 13 50 15" src="https://user-images.githubusercontent.com/6602401/199480665-bd0d20dd-489e-4b2a-933f-1d3d4a3e69b0.png">

Thread 1 Queue : com.apple.main-thread (serial)
#0	0x00000001850f995c in swift_retain ()
#1	0x00000001850fd1b0 in swift::metadataimpl::ValueWitnesses<swift::metadataimpl::SwiftRetainableBox>::initializeWithCopy(swift::OpaqueValue*, swift::OpaqueValue*, swift::TargetMetadata<swift::InProcess> const*) ()
#2	0x00000001073824fc in PrimitiveSequenceType<>.map<τ_0_0>(_:) at /app-ios/Pods/RxSwift/RxSwift/Traits/PrimitiveSequence/Single.swift:275
#3	0x000000010674f75c in ___lldb_unnamed_symbol6500 ()
#4	0x000000010679ca2c in ___lldb_unnamed_symbol8423 ()
#5	0x0000000106890de4 in ___lldb_unnamed_symbol14164 ()
#6	0x000000010678c38c in ___lldb_unnamed_symbol7964 ()
#7	0x00000001050cf990 in OndatoRoute<>.openOndatoModule(identificationId:flowDelegate:) at /app-ios/app/Modules/Ondato/OndatoRoute/OndatoRoute.swift:52
#8	0x00000001050846ac in protocol witness for OndatoRoute.openOndatoModule(identificationId:flowDelegate:) in conformance KYCRouter ()
#9	0x0000000104fee7fc in KYCPresenter.openOndatoModule() at /app-ios/app/Modules/KYC/Presenter/KYCPresenter+Ondato.swift:15
#10	0x0000000105044798 in KYCPresenter.didTapContinue() at /app-ios/app/Modules/KYC/Presenter/KYCPresenter.swift:92
#11	0x000000010504480c in protocol witness for KYCViewOutput.didTapContinue() in conformance KYCPresenter ()
#12	0x000000010508f834 in KYCViewController.buttonPressed(_:) at /app-ios/app/Modules/KYC/View/KYCViewController.swift:79
#13	0x000000010508f890 in @objc KYCViewController.buttonPressed(_:) ()
#14	0x0000000182e1e754 in -[UIApplication sendAction:to:from:forEvent:] ()
#15	0x0000000182f3d87c in -[UIControl sendAction:to:forEvent:] ()
#16	0x0000000182cd39f8 in -[UIControl _sendActionsForEvents:withEvent:] ()
#17	0x0000000182d6a998 in -[UIButton _sendActionsForEvents:withEvent:] ()
#18	0x0000000182fe24cc in -[UIControl touchesEnded:withEvent:] ()
#19	0x0000000182ae8188 in -[UIWindow _sendTouchesForEvent:] ()
#20	0x0000000182b17ca8 in -[UIWindow sendEvent:] ()
#21	0x0000000182cb8ac0 in -[UIApplication sendEvent:] ()
#22	0x0000000182aecc88 in __dispatchPreprocessedEventFromEventQueue ()
#23	0x0000000182ae1b4c in __processEventQueue ()
#24	0x0000000182ae6f68 in __eventFetcherSourceCallback ()
#25	0x00000001807004fc in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ ()
#26	0x000000018071062c in __CFRunLoopDoSource0 ()
#27	0x0000000180652834 in __CFRunLoopDoSources0 ()
#28	0x0000000180657f08 in __CFRunLoopRun ()
#29	0x000000018066b250 in CFRunLoopRunSpecific ()
#30	0x00000001a1196988 in GSEventRunModal ()
#31	0x0000000182e6ba94 in -[UIApplication _run] ()
#32	0x0000000182c04fd4 in UIApplicationMain ()
#33	0x0000000105079a90 in main at /app-ios/app/Application/main.swift:12
#34	0x00000001057404d0 in start ()

Xcode info:
Version 14.0.1 (14A400)

Pods Info:
  - OndatoSDK (2.1.0):
    - RxCocoa
  - RxCocoa (6.5.0):
    - RxRelay (= 6.5.0)
    - RxSwift (= 6.5.0)
  - RxRelay (6.5.0):
    - RxSwift (= 6.5.0)
  - RxSwift (6.5.0)

**Comment by blackchineykh** [comment]
Is there any resolution to this? We are having the same issue on iOS after updating to 2.1.0.

Thanks
