### ISSUE TITLE
flowDidFail function not called in version 2.1.4

### ISSUE THREAD

**Issue by glebpreger** [ondato/ondato-sdk-ios#9]
`OndatoFlowDelegate` function `flowDidFail(identificationId: String?, error: OndatoServiceError)` is not called on receiving  404 status code error

Ondato logs:

```
[OndatoSDK]   URLRequest: https://app-idvsapi-prod-ond.azurewebsites.net/v1/sessions 
[OndatoSDK]   HttpBody: {"identityVerificationId":"***"} 
[OndatoSDK]   YES URL REQUEST 
[OndatoSDK]   HTTP request failed with `404`. 
[OndatoSDK]   URLRequest: https://app-idvsapi-prod-ond.azurewebsites.net/v1/identity-verifications/***/complete 
[OndatoSDK]   HttpBody: null 
[OndatoSDK]   YES URL REQUEST 
```

**Comment by EditaKuzb** [comment]
Hi @glebpreger, 
please get in touch with our support team at support@ondato.com regarding this error. They will ask you for the setupId with which you have created "identityVerificationId" to check if everything is set correctly, so if you can, please specify the used setupId in your email.
